### ISSUE TITLE
MissingEnvironment sometimes isn't raised

### ISSUE THREAD

**Issue by ejholmes** [cloudtools/stacker#448]
We noticed this happen internally, where a key that was specified in remind.yaml, was missing in the env file, but stacker never raised `MissingEnvironment`. The reason it never gets raised, is because when we call [t.substitute](https://github.com/remind101/stacker/blob/e7e0e02575bbbc162249af7ceb2418f50b9b06d2/stacker/config/__init__.py#L84), if the `strings.Template` parser first hits a lookup (e.g. `${kms ...}`), then it'll raise a ValueError and fallback to calling [t.safe_substitute](https://github.com/remind101/stacker/blob/e7e0e02575bbbc162249af7ceb2418f50b9b06d2/stacker/config/__init__.py#L89), which will never raised an exception if there's a missing key in the env.

Here's a test that demonstrates the bug: https://github.com/remind101/stacker/commit/5e83ffb2de7fa38dae1ee9b5dae9f6c7b7767333

/cc @russellballestrini @phobologic

**Comment by phobologic** [comment]
Hrm, yeah, that's going to be a more annoying one.  Thanks for pointing this out.

**Comment by phobologic** [comment]
Pretty sure this is fixed, see this comment:

https://github.com/cloudtools/stacker/issues/579#issuecomment-403264995

Go ahead and re-open if I'm missing something :)
