### ISSUE TITLE
I can't define a environment based namespace anywhere except in an environment variable

### ISSUE THREAD

**Issue by colwilson** [cloudtools/stacker#509]
Despite being told that defining namespace in the the environment , I can't actually do it any other way. 

How can I get the config to use **myproject-dev**, **myproject-test** etc without using the environment?

**Comment by phobologic** [comment]
@colwilson What version of stacker?  What error are you getting?  Can you share your environment/config?  Thanks!

**Comment by colwilson** [comment]
1.1.1 I think, but it works now on 1.1.2

`stacker build -e namespace=myproject-dev stacks.yaml`

this can be closed now.

**Comment by phobologic** [comment]
I think this doc should explain it for the most part - let us know if it's missing something! https://stacker.readthedocs.io/en/latest/config.html#namespace

**Comment by colwilson** [comment]
I'm still confused. If I do:

`
stacker build -e namespace=myproject-dev stacks.yaml`

I get:

`
DEPRECATION WARNING: specifying namespace in the environment is deprecated. See https://stacker.readthedocs.io/en/latest/config.html#namespace for more info.
`

But if I add this to stacks.yaml:

`
namespace: ${prefix}
`

and run:

`
stacker build -e prefix=myproject-dev stacks.yaml
`

I get: 

`
stacker.exceptions.MissingEnvironment: Environment missing key namespace.
`

How am I supposed to define the namespace?

**Comment by phobologic** [comment]
Sorry @colwilson , this is obviously crazy late, but you should define the namespace in the config file, and then you should be able to define the variable in the environment file.  It should work just as well with `-e` though, I'm going to dig into that more now.

**Comment by phobologic** [comment]
Ok, using a namespace defined in an environment file works without any errors:

```
# cat dev.env
namespace: stacker-test-namespace
# cat stacker.yml
namespace: ${namespace}

stacks:
  - name: vpc
    class_path: stacker.tests.fixtures.mock_blueprints.Dummy
# stacker build --region us-east-1 ./dev.env ./stacker.yml
[2018-05-27T14:46:52] Using default AWS provider mode
[2018-05-27T14:46:54] vpc: skipped (nochange)
#
```

**Comment by phobologic** [comment]
Commenting out the namespace in the environment file, then using `-e` seems to work as well:

```
# cat dev.env
#namespace: stacker-test-namespace

# stacker build -e namespace=stacker-test-namespace --region us-east-1 ./dev.env ./stacker.yml
[2018-05-27T14:48:45] Using default AWS provider mode
[2018-05-27T14:48:47] vpc: skipped (nochange)
```

**Comment by phobologic** [comment]
Note - this is all with:

```
# stacker --version
stacker 1.3.0
```

**Comment by phobologic** [comment]
This may have been an issue with 1.1.0, but  I can't repeat in 1.3.  Going to go ahead and close.
