### ISSUE TITLE
upload_lambda_functions zips break on Windows 10

### ISSUE THREAD

**Issue by colwilson** [cloudtools/stacker#514]
I'm using stacker.hooks.aws_lambda.upload_lambda_functions under git bash on Win10.

Winzipped simple nodejs script with a node_modules uploaded and works find, but using the hook  the lambda function fails with the "Unable to import module 'handler': Error" which when Googled is often reported to be a zip problem (admittedly on stackless usually).

handler.js
`const cheerio = require('cheerio')

exports.handler = (event, context, callback) => { console.log('ok') }

`
cheerio is installed in the folder with npm

error message:

`START RequestId: 7694b65d-d457-11e7-b287-7bb492e39e34 Version: $LATEST
Unable to import module 'handler': Error
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/task/node_modules/cheerio/lib/parse.js:4:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
END RequestId: 7694b65d-d457-11e7-b287-7bb492e39e34
REPORT RequestId: 7694b65d-d457-11e7-b287-7bb492e39e34	Duration: 16.76 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 20 MB	
`

**Comment by troyready** [comment]
Curious if you're still experiencing this @colwilson ? If so, can you share the layout of the zip file (the CFN stack will show the S3 bucket where it was uploaded) and identify what should be different in it?

**Comment by phobologic** [comment]
Ping @colwilson

**Comment by colwilson** [comment]
Yes, sorry I'll update this when I get the environment set up again.

**Comment by colwilson-mo** [comment]
This breaks on Windows 10 even if I don;t use Stacker, so it is something else entirely.

We can close this.

**Comment by colwilson** [comment]
This breaks on Windows 10 even if I don;t use Stacker, so it is something else entirely.

We can close this.
