### ISSUE TITLE
Template line number reference should be displayed in error output

### ISSUE THREAD

**Issue by justinkillen** [cloudtools/stacker#579]
In particular, this would be nice when there is a stack dump.

E.g.:
14:13:44 [2018-04-06T14:13:44] stack-name: failed (dictionary update sequence element #4 has length 3; 2 is required)

^ This is a fairly hard thing to track down in the template, even with a stack trace.

**Comment by phobologic** [comment]
Thanks for the issue @justinkillen - sorry for the delay in response. Is this when using a blueprint or a template?  Do you have an example of a stack config/blueprint that would return this error?  I'm not certain where this error is coming from.  Thanks!

**Comment by justinkillen** [comment]
Typically, I see this when referencing a variable in the template yaml that has a typo, e.g. a security group defined in an environment file.  That situation produces a stack dump, but doesn’t indicate where in the yaml the actual problem is.  Aside from this specific cause, in general it would be nice for any kind of per-line parsing / variable replacement / etc include the line number that was being processed.

-Justin

**Comment by phobologic** [comment]
I'm not sure I follow - which template yaml are you referring to?

Sorry, the reason I want to dig into this particular issue is because without being able to easily reproduce this, I'm not certain where the issue might be.  If you could give me an example config, that'd be awesome.

**Comment by justinkillen** [comment]
As an example, take this sample.yaml:

  - name: service-asg-sg-rules
    class_path: blueprints.SecurityGroup.addIngressRules
    variables:
      rules:
        - GroupId=${output service-sg::GroupID},IpProtocol=tcp,FromPort=8080,ToPort=8080,SourceSecurityGroupId=${officenet_1}



and in the environment file common.env:

office_privatenet1: sg-12345678

*Notice that the template yaml is typo'd - it is officenet_1 when it should be office_privatenet1

If I run: "stacker build common.env sample.yaml -r us-east-1 -e namespace=common", I get this:

14:52:38 [2018-05-31T14:52:38] Couldn't resolve lookups in variable `rules`. Unknown lookup type: "None"
14:52:38 Traceback (most recent call last):
14:52:38   File "<path>/venv/lib/python2.7/site-packages/stacker/plan.py", line 88, in _run_once
14:52:38     status = self.fn(self.stack, status=self.status)
14:52:38   File "<path>/venv/lib/python2.7/site-packages/stacker/actions/build.py", line 269, in _launch_stack
14:52:38     stack.resolve(self.context, self.provider)
14:52:38   File "<path>/venv/lib/python2.7/site-packages/stacker/stack.py", line 175, in resolve
14:52:38     resolve_variables(self.variables, context, provider)
14:52:38   File "<path>/venv/lib/python2.7/site-packages/stacker/variables.py", line 77, in resolve_variables
14:52:38     variable.resolve(context, provider)
14:52:38   File "<path>/venv/lib/python2.7/site-packages/stacker/variables.py", line 146, in resolve
14:52:38     raise FailedVariableLookup(self.name, e)
14:52:38 FailedVariableLookup: Couldn't resolve lookups in variable `rules`. Unknown lookup type: "None"
14:52:38 [2018-05-31T14:52:38] common-service-asg-sg-rules: failed (Couldn't resolve lookups in variable `rules`. Unknown lookup type: "None")


It would be useful if the stack trace told me the line in sample.yaml that caused the 'Unknown lookup type: "None"' to occur

**Comment by phobologic** [comment]
Can I ask what version this is?  I just tested this (I believe I have a good test case) in master and couldn't reproduce it.

## Blueprint:
```
from troposphere import Ref, Region
from troposphere.cloudformation import WaitConditionHandle

from stacker.blueprints.base import Blueprint

class Foo(Blueprint):
    VARIABLES = {
        "StringVariable": {
            "type": str,
            "default": ""
        },
    }

    def create_template(self):
        self.template.add_resource(WaitConditionHandle("Dummy"))
        self.add_output("StringVariable", Value=Ref("StringVariable"))
        self.add_output("Region", Region)
```

## stacker.yml
```
namespace: ""

namespace_delimiter: ""

stacks:
  - name: param-test-stack
    class_path: blueprints.foo.Foo
    variables:
      StringVariable: ${my_string}
```

## dev.env
```
mystring: woot
```

## output of stacker run:
```
# stacker build --region us-east-1 ./dev.env ./stacker.yml
[2018-07-07T23:02:29] Using default AWS provider mode
Traceback (most recent call last):
  File "/Users/mike/venv/stackerdev/bin/stacker", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/mike/git/cloudtools/stacker/scripts/stacker", line 9, in <module>
    stacker.configure(args)
  File "/Users/mike/git/cloudtools/stacker/stacker/commands/stacker/__init__.py", line 36, in configure
    validate=True)
  File "/Users/mike/git/cloudtools/stacker/stacker/config/__init__.py", line 57, in render_parse_load
    pre_rendered = render(raw_config, environment)
  File "/Users/mike/git/cloudtools/stacker/stacker/config/__init__.py", line 102, in render
    raise exceptions.MissingEnvironment(e.args[0])
stacker.exceptions.MissingEnvironment: Environment missing key my_string.
```

(**Note:** I used `${my_string}` rather than `${mystring}`)

It doesn't tell you exactly where the issue is (though it should be fairly easy to find, since you know what the string is - could possibly be a little better, but might be a little tricky (I'll look into that).

Anyway, does that mostly cover what you're seeing?

**Comment by justinkillen** [comment]
Yes, I can confirm this is working in 1.3

Thanks!

**Comment by phobologic** [comment]
Thanks @justinkillen!
