### ISSUE TITLE
Way to get current region in blueprint class

### ISSUE THREAD

**Issue by marcusjv-po** [cloudtools/stacker#599]
Looking over the source code, I'm trying to see if there's a way to get the current AWS region the stack is being created in within a blueprint Class; i.e. 'self.region' or 'self.context.region'.

This could be useful in determining the AZs available in the region of execution, which would impact how I create subnets, etc in my VPC blueprint.

Thoughts?

**Comment by ejholmes** [comment]
@marcusjv-po generally, the best and most reliable way to do this is to use `Ref("AWS::Region")`. Something like `self.context.region` won't be reliable if you're using AWS profiles.

**Comment by russellballestrini** [comment]
You may also use `from troposphere import Region`

**Comment by marcusjv-po** [comment]
Thanks guys, but I think you're missing the point, so perhaps I'm not being super clear...  I would like to know which region the current stack is executing in, PRIOR to building stacks, so that the Blueprint I call can determine in advance the AZs available to it.

The current VPC blueprint provided by stacker_blueprints locks H/A and subnet provisioning (i.e., the total amount of subnets created corresponds to the number of AZs requested).  However, what if I want to create multiple subnets, for multiple applications, placing them in as many AZs as I can?

I'm not trying to use ('AWS::Region') in a template itself; I'm trying to get that info in advance and supply it to a blueprint method.

**Comment by ejholmes** [comment]
> However, what if I want to create multiple subnets, for multiple applications, placing them in as many AZs as I can?

Short answer is, you can't. At least not very easily. CloudFormation exposes the [GetAZs intrinsic function](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getavailabilityzones.html) but you can't really use this in a CloudFormation template to dynamically create multiple subnets.

If you really want to do this, you would need to resolve AZ's per region/account outside of stacker, and then pass it down as variables to the VPC blueprint. This could potentially be made easier if we exposed [DescribeAvailabilityZones](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeAvailabilityZones.html) as a lookup plugin.

In our experience, doing this dynamically usually creates more problems than it's worth (and GetAZs is potentially harmful, since it's return value is not always determinstic).

**Comment by marcusjv-po** [comment]
My idea was to do something like this (within a VPC blueprint):

`
class blah(Blueprint):
    def foobar(self):
        vars = self.get_variables()
        ec2 = boto3.client('ec2', region_name=self.context.region)
        azs = ec2.describe_availability_zones()['AvailabilityZones']
        desired_ha = vars.get('AZCount')
        if desired_ha > azs:
            bail
`
etc.  

I get that GetAZs will return different things, and if you specify more subnets than AZs, the way the VPC blueprint currently works, CF complains that the index position is unavailable (Select(i, GetAZs)).   

Reading your blog post, did the 'networks' blueprint make it's way into the stacker_blueprints repo?  Thanks much to all those at Remind for creating such a great tool, btw!

**Comment by russellballestrini** [comment]
@marcusjv-po I think @phobologic is working on a version for the `stacker_blueprints` repo.

@phobologic do you have an update on that?

**Comment by phobologic** [comment]
@marcusjv-po @russellballestrini should have it done tonight/tomorrow, I'm working on it right now actually :)

**Comment by phobologic** [comment]
Ok, @russellballestrini @marcusjv-po - https://github.com/cloudtools/stacker_blueprints/pull/2

I think I like the interface well enough, but not 100% sure on it.  Would love comments.  Basically you'd create a stack per subnet.  While this means extra stacks, it gives you a bit more control, and makes things a little more explicit.

Anyway, let me know what you think!

**Comment by russellballestrini** [comment]
This looks solid to me! Would you mind putting in a doc string with some example YAML to show to use this to create a couple subnets (2 public/2 private) or maybe even paired with `vpc.Vpc2`?

That or maybe a separate example doc is in order.

**Comment by phobologic** [comment]
Added an example in the https://github.com/cloudtools/stacker_blueprints/tree/master/conf/example_vpc directory.

**Comment by phobologic** [comment]
@marcusjv-po is there anything left in this issue that you feel needs to be resolved?  Or can we close it?  Thanks!

**Comment by marcusjv-po** [comment]
@phobologic Thanks very much for the new vpc and network blueprints; I'll have a look at incorporating them into my provisioning strategy.  Everything LGTM.

**Comment by phobologic** [comment]
Cool - I'm going to go ahead and close this.  If you think it needs to remain open, please feel free to re-open it @marcusjv-po!
