### ISSUE TITLE
Variables & User Experience

### ISSUE THREAD

**Issue by brettswift** [cloudtools/stacker#603]
I'm brand new here and evaluating stacker.  I love a lot of things already.

I have one behaviour I can't seem to grasp the intent of. 

I get that the `stack.yaml`  has variable definitions - and those map into the stacker classes `VARIABLES` dictionary.  
I also get that environment variables or cli overrides can replace template variables, similar to templating behaviour. 

Question: 

What is the common practice with parameters that are environment specific,  and as a template/stack author you want to declare as "must override".   The intent being that a "stack consumer" can't deploy your stack without specifying a parameter? 

In a lot of cases the author and consumer are the same person but I'm just using it to help with perspective on this question.

One example is  `VpcId`.   I probably want this to be environment specific, and don't want a default.

I could come up with a scheme like: 

stack.yaml
```
~ 
stacks:
   -name: Test
     variables:
         VpcId: 'must-override'
```

template.py
```
~
 VARIABLES = {
        'VpcId': {'type': EC2VPCId, 'description': 'Vpc Id'},
```

Your output isn't very friendly.  It'll say something like `'must-override' is not a valid VpcId`.

What do people do in this case? 

The reason I ask is if you put a variable in a template and someone comes by to run it - not realizing they should define their own environment file with their own VPC..  (maybe a bad usage example)..  but it might be hard to do. 

Other solutions might be 1) have something generate your stack.yaml (heavier lift).

I think I'm missing something in the documentation or examples.   If so - what am I missing?!

**Comment by phobologic** [comment]
Hey @brettswift, thanks for checking out stacker and submitting this issue.  I think I may be misunderstanding your intent, so let me know if this doesn't fit - basically, if you do not provide a default value for a variable, it is then required that it be defined in the stacker config.

If you want to provide a stacker config that shows what variables should be defined, I think the best bet is to use the environment syntax to show that:

```
stacks:
  - name: Test
    variables:
      VpcId: ${vpc_id}
```
If a `vpc_id` is not provided in the environment, then the user will get the following error:

```
# stacker build --region us-east-1 ./dev.env ./stacker.yml
[2018-05-28T10:24:13] Using default AWS provider mode
Traceback (most recent call last):
  File "/Users/mike/venv/stest/bin/stacker", line 9, in <module>
    stacker.configure(args)
  File "/Users/mike/venv/stest/lib/python2.7/site-packages/stacker/commands/stacker/__init__.py", line 33, in configure
    validate=True)
  File "/Users/mike/venv/stest/lib/python2.7/site-packages/stacker/config/__init__.py", line 47, in render_parse_load
    pre_rendered = render(raw_config, environment)
  File "/Users/mike/venv/stest/lib/python2.7/site-packages/stacker/config/__init__.py", line 92, in render
    raise exceptions.MissingEnvironment(e.args[0])
stacker.exceptions.MissingEnvironment: Environment missing key vpc_id.
```

Let me know if that answers your question!

**Comment by brettswift** [comment]
Perfect, thank you.  I missed the anchor notation in the stack definition file. 

I also made some assumptions that you could override anything by just using an environment file, but without the  `${}` notation the environment override will not be put into the stack.  Stacker is silent in that it doesn't warn / error when there's a param in the environment file that isn't going to have any effect. 

It might be nice to see an error here, although this could be tracked in another issue. 

Thanks for the help!

**Comment by phobologic** [comment]
> Stacker is silent in that it doesn't warn / error when there's a param in the environment file that isn't going to have any effect.
>
> It might be nice to see an error here, although this could be tracked in another issue.

This is actually something of a feature.  It lets you have anchor'd dictionaries that you can pass around to any stack, and not have to worry about whether or not they use the entire dictionary.  That said, it can cause some annoying issues when it comes to typos in variable names, but usually those are fairly easy to find - it only becomes a problem when defaults are available.

It's a toss up between flexibility and correctness, and it'd be hard to take the feature away from some folks.

Thanks again for the issue!
