### ISSUE TITLE
Support for conditional variable value resolution?

### ISSUE THREAD

**Issue by mfoertsch1** [cloudtools/stacker#604]
Please forgive me if this functionality already exists or there is a way to replicate something like it with the current feature set.

I have a scenario where I would like to be able to optionally define a variable and use that variable if defined. If the variable is not defined I'd like to default to a lookup, so something like:
```
  - name: service-foo
    ...stuff...
    variables:
      ...stuff...
        ServiceBarUrl: ${definedcheck ${service_bar_url} : ${xref: service-stack-bar::InvokeUrl}}
```
If service_bar_url has been defined it is used and the xref lookup is skipped, otherwise the xref lookup is resolved.

**Comment by phobologic** [comment]
You should be able to use the `${default}` lookup for this.  Sorry for the delayed reply!  So something like:

`${default ${service_bar_url}::${xref service-stack-bar::InvokeUrl}}`

**Comment by mfoertsch1** [comment]
No worries, for some reason I didn't get an email notification =(. Tyvm, this is exactly what I needed.

**Comment by phobologic** [comment]
Glad it works for you!  Let us know if you run into any other questions :)
