### ISSUE TITLE
Suggestion: Add region to logging info messages

### ISSUE THREAD

**Issue by GarisonLotus** [cloudtools/stacker#675]
This is an idea that came up at the office, and I kind of dig it.  If we have multi-region deployments or execute stacker build in a CI pipeline separately against different regions, this would be very helpful in the logged output determine which region was the message related to.

thoughts?

**Comment by russellballestrini** [comment]
@GarisonLotus I added the ability to define custom logging a few releases, ago. Could this issue be closed?

https://stacker.readthedocs.io/en/latest/config.html#custom-log-formats
