### ISSUE TITLE
base64 lookup contents are repr'd as byte strings causing AWS to reject it

### ISSUE THREAD

**Issue by Phrohdoh** [cloudtools/stacker#693]
I encountered this when creating an `AWS::AutoScaling::LaunchConfiguration` in a CloudFormation template with `UserData` coming from a file on-disk.

In `stacker.yaml`:

```
UserData: ${file base64:file://userdata/asg-mount-efs.bash}
```

Results in the following being passed to the template as a parameter:

```
b'mybase64text'
```

Instead of the expected:

```
mybase64text
```

**Comment by russellballestrini** [comment]
@Phrohdoh are you running stacker with Python 3?

**Comment by russellballestrini** [comment]
My guess is the issue is in this function (`parameterized_codec`): https://github.com/cloudtools/stacker/blob/master/stacker/lookups/handlers/file.py#L149-L171

**Comment by Phrohdoh** [comment]
Yes, `Python 3.7.1`.

**Comment by jklobo** [comment]
Were you able to work around this issue? I'm seeing the exact same behavior

**Comment by russellballestrini** [comment]
@xiaket do you mind taking a look at this defect? Seems to only happen with Python 3.

**Comment by troyready** [comment]
@jklobo can you put together a reproduction example? gist the stacker config and template/file lookup files?

**Comment by acmcelwee** [comment]
I fixed this in https://github.com/cloudtools/stacker/pull/742
