### ISSUE TITLE
stacker build fails with version 1.7

### ISSUE THREAD

**Issue by dmongit** [cloudtools/stacker#726]
Using an AWS buildspec file, I have a pip install stacker command that installs stacker just fine.

When I run stacker build -r <mystuff> <moreofmystuff> stacker.yml, I get an error. I tracked the error down to s3transfer not being happy with the version of boto3. 

When I revert back to install pip install stacker 1.6, everything works.

Error Message:

> File "/usr/local/lib/python2.7/dist-packages/s3transfer/utils.py", line 27, in <module>
>  from botocore.exceptions import ReadTimeoutError
> ImportError: cannot import name ReadTimeoutError

**Comment by phobologic** [comment]
@dmongit thanks for the report - can you share the versions of boto3 and botocore that you have installed that's causing the issue?  I see `ReadTimeoutError` in botocore.exceptions going back as far as `1.12.31` at least.

**Comment by dmongit** [comment]
@phobologic Not sure about botocore. Since I'm running it off of AWS CI/CD, I'm at the mercy of what is already installed on that build box? I'm using image aws/codebuild/nodejs:6.3.1 for the build.

Here are snippets from my logs, first using stacker 1.7 and second using 1.6 as a comparison.

stacker 1.7 when things failed
Collecting boto3>=1.9.111<2.0 (from stacker)
Collecting s3transfer<0.3.0,>=0.2.0 (from boto3>=1.9.111<2.0->stacker)
Successfully installed boto3-1.9.130 s3transfer-0.2.0

Latests, explicitly using stacker 1.6:
Collecting boto3<1.8.0,>=1.7.0 (from stacker<1.6.1,>=1.6.0)
s3transfer<0.2.0,>=0.1.10->boto3<1.8.0,>=1.7.0->stacker<1.6.1,>=1.6.0)
Requirement already satisfied: botocore in /usr/local/lib/python2.7/dist-packages (from stacker)
Successfully installed boto3-1.7.84

**Comment by josjaf** [comment]
I'm getting this error too

**Comment by troyready** [comment]
You can work around this for now by changing your `pip install stacker` line to:

```
pip install 'botocore>=1.12.111'
pip install stacker
```

I've opened a PR (#729 ) to make that work out of the box again

**Comment by phobologic** [comment]
Thanks @troyready - I am going to do a dot release to clear this up tonight.
