### ISSUE TITLE
KMS lookups give values $VAL wrapped as "b'$VAL'" when using python 3

### ISSUE THREAD

**Issue by hauntingEcho** [cloudtools/stacker#755]
While attempting to encrypt a password 'hello!' per the directions [here](https://stacker.readthedocs.io/en/latest/lookups.html#kms-lookup):
1. the command given for encryption fails entirely
2. after getting encryption working, Stacker populated incorrect values

using the suggested encryption command `aws kms encrypt --key-id alias/DbConnectionKey --plaintext 'hello!' --output text --query CiphertextBlob` results in:
```
Invalid base64: "hello!"
```

From there, I attempted to use `aws kms encrypt --key-id alias/DbConnectionKey --plaintext fileb://<(echo -n 'hello!') --output text --query CiphertextBlob` and used the result to create a secret via Stacker.  In this secret, I see:

![image](https://user-images.githubusercontent.com/1661988/77974677-78d79080-72bd-11ea-8f52-74234e68cda1.png)

Does this need a different configuration than the one from the docs, or is there another way I should be doing this?  I'm currently using Stacker 1.7.0 on python 3.5.3.  I've also tried dropping the '!' off the end and received the same behavior with just "hello".

**Comment by hauntingEcho** [comment]
after uninstalling via pip3 and reinstalling via pip2, the issue only affects Python 3. For what it's worth, `aws --version` gives me `aws-cli/2.0.0 Python/3.7.3 Linux/4.4.0-17763-Microsoft botocore/2.0.0dev4`

**Comment by hauntingEcho** [comment]
This has been resolved with 1.7.1

**Comment by baryal1299** [comment]
> This has been resolved with 1.7.1

Still seeing the same issue, is this fixed for python 3?

**Comment by hauntingEcho** [comment]
you're right, I hadn't cleaned out my python2 installation and am seeing this issue again

**Comment by bmcoelho** [comment]
Hi guys,

Any chance to fix this in the next release? All the secrets are now showing as **b'<secret>'**

Thanks

**Comment by hauntingEcho** [comment]
It looks like this should be fixed by your PR #765 , pending release ( #766 )

**Comment by phobologic** [comment]
I'll go ahead and get a dot release out by this weekend.

**Comment by phobologic** [comment]
https://github.com/cloudtools/stacker/releases/tag/1.7.2 - released, sorry for the delay!
