### ISSUE TITLE
problems running the make file.

### ISSUE THREAD

**Issue by sathishjayapal** [cloudtools/stacker#758]
I followed the cookbook to create a simple stacker template. I'm using the cloud 9 env to run the simple template. I could see the code is generated correctly and there are respective folders. But when I run the make command for dev. I get this following error., 

```
[SolverProblemError]
Because stacker-blueprints (1.0.8) depends on troposphere (>=2.3.2) which doesn't match any versions, stacker-blueprints is forbidden.
```

Any ideas when I might be missing., I did verify that troposhere is installed in my env. Thanks for helping.

**Comment by phobologic** [comment]
This was an issue with stacker_cookiecutter that has been fixed, closing.  Thanks for the report!
