### ISSUE TITLE
New Stacker Release version

### ISSUE THREAD

**Issue by bmcoelho** [cloudtools/stacker#766]
The most current version of Stacker was released 3 months ago, and there have been important bugfixes since - in particular, #765. Will there be a new release soon?

**Comment by troyready** [comment]
Stacker is relatively feature-complete now and does not do releases often. To use recent features, you may need to rely on installing from your own branch or fork. We've discussed a CD pipeline in the past but could not get consensus on deploying it.

I outlined another alternative [in this comment](https://github.com/cloudtools/stacker/issues/759#issuecomment-673149717)

**Comment by baryal1299** [comment]
Do we have an estimated time for next release?

**Comment by phobologic** [comment]
Sorry for the delay, https://github.com/cloudtools/stacker/releases/tag/1.7.2 is released.
